name = "MPITestImages"
uuid = "67a05f95-e8e3-406b-b1ec-9f1919b23209"
authors = ["Jonas Schumacher <jonas.schumacher@imte.fraunhofer.de> and contributors"]
version = "0.1.4"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Compat = "3, 4"
DocStringExtensions = "0.8, 0.9"
Documenter = "0.27"
FileIO = "1"
Images = "0.23, 0.24, 0.25"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
